version: "3.9"
services:
  db:
    image: postgres:15.0
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=hello_aiohttp
      - POSTGRES_PASSWORD=hello_aiohttp
      - POSTGRES_DB=aiohttp_db
