# API-запросы

@baseUrl = http://127.0.0.1:7000

###

# проверка работоспособности и состояния через запрос на главную страницу
{{baseUrl}}/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/ads/
Content-Type: application/json

{
  "title": "Продам дом",
  "description": "Самый красивый дом в районе.",
  "owner": "Пользователь_3",
}

###

# получение объявлений
GET {{baseUrl}}/advertisements
Content-Type: application/json

###


# получение объявления
GET {{baseUrl}}/ads/1
Content-Type: application/json

###

# обновление объявления
PATCH {{baseUrl}}/ads/1/
Content-Type: application/json

{
  "title": "Продам дом с участком",
  "description": "Самый красивый дом в районе. 3 этажа. 500 м.кв."
}

###

# удаление объявления
DELETE {{baseUrl}}/ads/2/
Content-Type: application/json

###